name: Build libFMS with cmake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        omp-flags: [ -DOPENMP=on, -DOPENMP=off ]
        libyaml-flag: [ "", -DWITH_YAML=on ]
        io-flag: [ "", -DUSE_DEPRECATED_IO=on ]
    container:
      image: noaagfdl/hpc-me.ubuntu-minimal:cmake
      env:
        CMAKE_FLAGS: "${{ matrix.omp-flags }} ${{ matrix.io-flag  }} ${{ matrix.libyaml-flag }} -D64BIT=on"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Generate makefiles with CMake
      run: cmake $CMAKE_FLAGS .
    - name: Build the library
      run: make
